import { MigrationInterface, QueryRunner } from "typeorm";

export class InitialSchema1783321035884 implements MigrationInterface {
    name = 'InitialSchema1783321035884'

    public async up(queryRunner: QueryRunner): Promise<void> {
        // The dev/prod docker-compose init script already enables these (see
        // docker/postgres/init/01-extensions.sql); repeated here so this
        // migration is self-sufficient against any fresh Postgres 16+ target.
        await queryRunner.query(`CREATE EXTENSION IF NOT EXISTS "uuid-ossp"`);
        await queryRunner.query(`CREATE EXTENSION IF NOT EXISTS "postgis"`);
        await queryRunner.query(`CREATE EXTENSION IF NOT EXISTS "pg_trgm"`);
        await queryRunner.query(`CREATE TYPE "public"."click_payment_transaction_status_enum" AS ENUM('pending', 'success', 'cancelled')`);
        await queryRunner.query(`CREATE TABLE "click_payment_transaction" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "orderId" uuid NOT NULL, "clickTransId" character varying, "amount" numeric(14,2) NOT NULL, "status" "public"."click_payment_transaction_status_enum" NOT NULL DEFAULT 'pending', "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_278ea0f8c7a8f4b09505bc57402" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_2583a18597840d00d7f2f9604c" ON "click_payment_transaction"  ("orderId") `);
        await queryRunner.query(`CREATE INDEX "IDX_eed5678b20baa095e18ceb464a" ON "click_payment_transaction"  ("clickTransId") `);
        await queryRunner.query(`CREATE TABLE "app_releases" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "version" character varying(32) NOT NULL, "fileKey" character varying(256) NOT NULL, "sizeBytes" integer NOT NULL, "notes" text, "isLatest" boolean NOT NULL DEFAULT false, "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_e5b28b6fe128172639b75251cd1" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_87c877cbe4318d54eda893b7af" ON "app_releases"  ("isLatest") `);
        await queryRunner.query(`CREATE TABLE "categories" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "slug" character varying(128) NOT NULL, "nameUzLatn" character varying(128) NOT NULL, "nameUzCyrl" character varying(128) NOT NULL, "nameRu" character varying(128) NOT NULL, "iconUrl" character varying(512), "sortOrder" integer NOT NULL DEFAULT '0', "isActive" boolean NOT NULL DEFAULT true, "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "mpath" character varying DEFAULT '', "parentId" uuid, CONSTRAINT "PK_24dbc6126a28ff948da33e97d3b" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_420d9f679d41281f282f5bc7d0" ON "categories"  ("slug") `);
        await queryRunner.query(`CREATE TABLE "chat_templates" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "shopId" uuid, "text" text NOT NULL, "isSystem" boolean NOT NULL DEFAULT false, "sortOrder" integer NOT NULL DEFAULT '0', "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_996127c93a84fc1ee5d352a934d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_e973a07c51fc96d7e0ccb0faa1" ON "chat_templates"  ("shopId") `);
        await queryRunner.query(`CREATE TABLE "contact_inquiries" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying(128) NOT NULL, "phone" character varying(32) NOT NULL, "message" text NOT NULL, "isRead" boolean NOT NULL DEFAULT false, "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_3e96c0b8474f8f92d8d03843153" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_189c4035e45c65e0585bf05ad5" ON "contact_inquiries"  ("isRead") `);
        await queryRunner.query(`CREATE TABLE "debt_payments" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "shopId" uuid NOT NULL, "customerPhone" character varying(32) NOT NULL, "amount" integer NOT NULL, "note" text, "createdByUserId" uuid, "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_53e3004f438dfaee6e6c67b5ce5" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_dd551fbae9b5c6d1a15a5c043e" ON "debt_payments"  ("shopId", "customerPhone") `);
        await queryRunner.query(`CREATE INDEX "IDX_8c90ebeaecf5a829dc3a9bf779" ON "debt_payments"  ("shopId") `);
        await queryRunner.query(`CREATE TABLE "debts" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "shopId" uuid NOT NULL, "customerName" character varying(128) NOT NULL, "customerPhone" character varying(32) NOT NULL, "lines" jsonb NOT NULL DEFAULT '[]'::jsonb, "itemsTotal" integer NOT NULL DEFAULT '0', "extraCharge" integer NOT NULL DEFAULT '0', "total" integer NOT NULL, "note" text, "stockDecremented" boolean NOT NULL DEFAULT false, "createdByUserId" uuid, "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_4bd9f54aab9e59628a3a2657fa1" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_861450059455369c652646c0cd" ON "debts"  ("shopId", "customerPhone") `);
        await queryRunner.query(`CREATE INDEX "IDX_18f03a4157df01362487561a89" ON "debts"  ("shopId") `);
        await queryRunner.query(`CREATE TABLE "notification_templates" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying(128) NOT NULL, "title" character varying(128) NOT NULL, "body" character varying(512) NOT NULL, "richBody" text, "imageUrl" character varying(512), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_76f0fc48b8d057d2ae7f3a2848a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."users_status_enum" AS ENUM('active', 'blocked')`);
        await queryRunner.query(`CREATE TABLE "users" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "phone" character varying(32) NOT NULL, "name" character varying(128), "avatarUrl" character varying(512), "status" "public"."users_status_enum" NOT NULL DEFAULT 'active', "isSellerApproved" boolean NOT NULL DEFAULT false, "isAdmin" boolean NOT NULL DEFAULT false, "roles" jsonb NOT NULL DEFAULT '["customer"]'::jsonb, "favoriteShopIds" jsonb NOT NULL DEFAULT '[]'::jsonb, "favoriteProductIds" jsonb NOT NULL DEFAULT '[]'::jsonb, "lastLoginAt" TIMESTAMP WITH TIME ZONE, "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_a3ffb1c0c8416b9fc6f907b7433" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_a000cca60bcf04454e72769949" ON "users"  ("phone") `);
        await queryRunner.query(`CREATE TABLE "notifications" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "userId" uuid NOT NULL, "title" character varying(128) NOT NULL, "body" character varying(512) NOT NULL, "data" jsonb NOT NULL DEFAULT '{}'::jsonb, "kind" character varying(32) NOT NULL DEFAULT 'general', "isRead" boolean NOT NULL DEFAULT false, "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_6a72c3c0f683f6462415e653c3a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_5340fc241f57310d243e5ab20b" ON "notifications"  ("userId", "isRead") `);
        await queryRunner.query(`CREATE INDEX "IDX_21e65af2f4f242d4c85a92aff4" ON "notifications"  ("userId", "createdAt") `);
        await queryRunner.query(`CREATE TABLE "shops" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "ownerId" uuid NOT NULL, "name" character varying(128) NOT NULL, "description" text, "photos" jsonb NOT NULL DEFAULT '[]'::jsonb, "address" character varying(512) NOT NULL, "latitude" double precision NOT NULL, "longitude" double precision NOT NULL, "workingHours" jsonb NOT NULL DEFAULT '[]'::jsonb, "holidays" jsonb NOT NULL DEFAULT '[]'::jsonb, "isOpenManual" boolean NOT NULL DEFAULT true, "minOrderPrice" integer NOT NULL DEFAULT '0', "deliveryZone" jsonb NOT NULL DEFAULT '{"maxKm":2,"freeKm":2,"pricingType":"flat","pricePerStep":0}'::jsonb, "deliveryPolygon" jsonb, "freeDeliveryPolygon" jsonb, "blockedUserIds" jsonb NOT NULL DEFAULT '[]'::jsonb, "ratingAverage" double precision NOT NULL DEFAULT '0', "ratingCount" integer NOT NULL DEFAULT '0', "isActive" boolean NOT NULL DEFAULT true, "deactivatedByDebt" boolean NOT NULL DEFAULT false, "ownerOrdersSeenAt" TIMESTAMP WITH TIME ZONE, "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_3c6aaa6607d287de99815e60b96" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_d38394b318a963074a1db6d5ff" ON "shops"  ("isActive") `);
        await queryRunner.query(`CREATE INDEX "IDX_9f222a91f08322c9d08a1b443b" ON "shops"  ("ownerId") `);
        await queryRunner.query(`CREATE TABLE "user_addresses" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "userId" uuid NOT NULL, "label" character varying(64) NOT NULL, "address" character varying(512) NOT NULL, "latitude" double precision NOT NULL, "longitude" double precision NOT NULL, "notes" character varying(256), "isDefault" boolean NOT NULL DEFAULT false, "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_8abbeb5e3239ff7877088ffc25b" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_781afdedafe920f331f6229cb6" ON "user_addresses"  ("userId") `);
        await queryRunner.query(`CREATE TABLE "global_products" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "barcode" character varying(64), "name" character varying(256) NOT NULL, "brand" character varying(128), "unitType" character varying(16) NOT NULL DEFAULT 'piece', "unitSize" double precision NOT NULL DEFAULT '1', "categoryId" uuid, "photos" jsonb NOT NULL DEFAULT '[]'::jsonb, "description" text, "createdBySellerId" uuid, "isVerified" boolean NOT NULL DEFAULT false, "isActive" boolean NOT NULL DEFAULT true, "usageCount" integer NOT NULL DEFAULT '0', "parentGlobalProductId" uuid, "ownerShopId" uuid, "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_cb1230c5cd28d2855eff2cdcd99" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_093da3874aeff5ab90cb7cb8ca" ON "global_products"  ("ownerShopId") `);
        await queryRunner.query(`CREATE INDEX "IDX_4bf7609c1c77d52950be6acc5a" ON "global_products"  ("parentGlobalProductId") `);
        await queryRunner.query(`CREATE INDEX "IDX_f9d3e6d9c5bf426e72e8b18d48" ON "global_products"  ("isActive", "usageCount") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_03af0d5bb5d7cfb8814b9c36ab" ON "global_products"  ("barcode") `);
        await queryRunner.query(`CREATE TABLE "product_variants" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "shopId" uuid NOT NULL, "globalProductId" uuid NOT NULL, "price" integer NOT NULL, "discountPrice" integer, "stock" integer NOT NULL DEFAULT '0', "lowStockThreshold" integer NOT NULL DEFAULT '5', "criticalThreshold" integer, "expiryDate" date, "ratingAverage" double precision NOT NULL DEFAULT '0', "ratingCount" integer NOT NULL DEFAULT '0', "isActive" boolean NOT NULL DEFAULT true, "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "UQ_d2aae1259b78f4d50686e3f0090" UNIQUE ("shopId", "globalProductId"), CONSTRAINT "PK_281e3f2c55652d6a22c0aa59fd7" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_e1f34b679c60762b30a747310e" ON "product_variants"  ("globalProductId") `);
        await queryRunner.query(`CREATE INDEX "IDX_94d7217a650df509004c9ef458" ON "product_variants"  ("shopId", "isActive", "createdAt") `);
        await queryRunner.query(`CREATE INDEX "IDX_f0fc8814e8aded9e9ee5793199" ON "product_variants"  ("shopId") `);
        await queryRunner.query(`CREATE TABLE "order_items" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "orderId" uuid NOT NULL, "productVariantId" uuid NOT NULL, "productName" character varying(256) NOT NULL, "quantity" integer NOT NULL, "unitPrice" integer NOT NULL, "lineTotal" integer NOT NULL, "returnedQuantity" integer NOT NULL DEFAULT '0', "costOfGoods" integer NOT NULL DEFAULT '0', "appliedPromotionId" uuid, "promotionDiscountAmount" integer NOT NULL DEFAULT '0', CONSTRAINT "PK_005269d8574e6fac0493715c308" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_f1d359a55923bb45b057fbdab0" ON "order_items"  ("orderId") `);
        await queryRunner.query(`CREATE TYPE "public"."orders_channel_enum" AS ENUM('delivery', 'in_store')`);
        await queryRunner.query(`CREATE TYPE "public"."orders_status_enum" AS ENUM('new', 'accepted', 'preparing', 'delivering', 'delivered', 'cancelled')`);
        await queryRunner.query(`CREATE TYPE "public"."orders_paymentmethod_enum" AS ENUM('cash', 'click_online')`);
        await queryRunner.query(`CREATE TYPE "public"."orders_paymentstatus_enum" AS ENUM('not_required', 'pending', 'paid', 'failed')`);
        await queryRunner.query(`CREATE TABLE "orders" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "userId" uuid, "shopId" uuid NOT NULL, "deliveryAddressId" uuid, "channel" "public"."orders_channel_enum" NOT NULL DEFAULT 'delivery', "orderNumber" character varying(32) NOT NULL, "subTotal" integer NOT NULL, "deliveryFee" integer NOT NULL, "total" integer NOT NULL, "distanceKm" double precision NOT NULL, "status" "public"."orders_status_enum" NOT NULL DEFAULT 'new', "paymentMethod" "public"."orders_paymentmethod_enum" NOT NULL DEFAULT 'cash', "paymentStatus" "public"."orders_paymentstatus_enum" NOT NULL DEFAULT 'not_required', "acceptedByStaffId" uuid, "assignedStaffId" uuid, "deliveredByStaffId" uuid, "timeline" jsonb NOT NULL DEFAULT '[]'::jsonb, "cancellationReason" text, "returnReason" text, "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_710e2d4957aa5878dfe94e4ac2f" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_1f4b9818a08b822a31493fdee9" ON "orders"  ("createdAt") `);
        await queryRunner.query(`CREATE INDEX "IDX_775c9f06fc27ae3ff8fb26f2c4" ON "orders"  ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_7fc658e494680d44c3cc59b31b" ON "orders"  ("shopId") `);
        await queryRunner.query(`CREATE INDEX "IDX_151b79a83ba240b0cb31b2302d" ON "orders"  ("userId") `);
        await queryRunner.query(`CREATE TABLE "chat_messages" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "orderId" uuid NOT NULL, "senderUserId" uuid NOT NULL, "fromShop" boolean NOT NULL, "text" text NOT NULL, "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_40c55ee0e571e268b0d3cd37d10" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_c13440c7163e7d349fee5ff8a5" ON "chat_messages"  ("orderId", "createdAt") `);
        await queryRunner.query(`CREATE TABLE "reviews" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "userId" uuid NOT NULL, "productVariantId" uuid NOT NULL, "orderId" uuid NOT NULL, "stars" smallint NOT NULL, "text" text, "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "UQ_b1232b6a0f3690cb66b823eeadd" UNIQUE ("userId", "productVariantId", "orderId"), CONSTRAINT "PK_231ae565c273ee700b283f15c1d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_2fd6e4869fe14144d8176e4360" ON "reviews"  ("productVariantId") `);
        await queryRunner.query(`CREATE TABLE "seller_balances" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "sellerId" uuid NOT NULL, "pendingBalance" numeric(15,2) NOT NULL DEFAULT '0', "availableBalance" numeric(15,2) NOT NULL DEFAULT '0', "debtBalance" numeric(15,2) NOT NULL DEFAULT '0', "debtDueDate" date, "lastDebtReminderAt" TIMESTAMP WITH TIME ZONE, "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_a8e1ce8caaab5a0bd3886ebaf36" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_f8e76a6290799a7971133b2fa2" ON "seller_balances"  ("sellerId") `);
        await queryRunner.query(`CREATE TYPE "public"."seller_transactions_type_enum" AS ENUM('cash_order_commission', 'online_order_pending', 'pending_settled', 'debt_repaid', 'withdrawal_requested', 'withdrawal_completed', 'prime_payment', 'admin_adjustment', 'refund_debit')`);
        await queryRunner.query(`CREATE TABLE "seller_transactions" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "sellerId" uuid NOT NULL, "orderId" uuid, "type" "public"."seller_transactions_type_enum" NOT NULL, "amount" numeric(15,2) NOT NULL, "commissionRate" numeric(5,2), "commissionAmount" numeric(15,2), "status" character varying(16) NOT NULL DEFAULT 'settled', "settlesAt" TIMESTAMP WITH TIME ZONE, "description" text NOT NULL, "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_b19c3b577e589dde9af4fa0768e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_398f34204057deff8f37060f4a" ON "seller_transactions"  ("orderId") `);
        await queryRunner.query(`CREATE INDEX "IDX_b9b774cc499fe064311e69b788" ON "seller_transactions"  ("sellerId", "createdAt") `);
        await queryRunner.query(`CREATE TYPE "public"."withdrawal_requests_status_enum" AS ENUM('pending', 'processing', 'completed', 'rejected')`);
        await queryRunner.query(`CREATE TABLE "withdrawal_requests" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "sellerId" uuid NOT NULL, "amount" numeric(15,2) NOT NULL, "bankCardNumber" character varying(16) NOT NULL, "bankCardHolderName" character varying(128) NOT NULL, "status" "public"."withdrawal_requests_status_enum" NOT NULL DEFAULT 'pending', "requestedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "processedAt" TIMESTAMP WITH TIME ZONE, "processedByAdminId" uuid, "adminNote" text, CONSTRAINT "PK_e1b3734a3f3cbd46bf0ad7eedb6" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_960e0ec5dbbb52352401b84b6b" ON "withdrawal_requests"  ("sellerId", "status") `);
        await queryRunner.query(`CREATE TABLE "prime_plans" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying(64) NOT NULL, "monthlyPrice" numeric(15,2) NOT NULL, "yearlyPrice" numeric(15,2), "commissionRate" numeric(5,2) NOT NULL, "description" text, "isActive" boolean NOT NULL DEFAULT true, "sortOrder" integer NOT NULL DEFAULT '0', "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_bdddf3a18aa1d0a923184e097a4" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "seller_subscriptions" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "sellerId" uuid NOT NULL, "planId" uuid NOT NULL, "commissionRateSnapshot" numeric(5,2) NOT NULL, "priceSnapshot" numeric(15,2) NOT NULL, "startDate" date NOT NULL, "endDate" date NOT NULL, "isActive" boolean NOT NULL DEFAULT true, "cancelledAt" TIMESTAMP WITH TIME ZONE, "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_c993bcf8d50b0082d90a55407e8" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_ab10ec10133b7e1926a824880b" ON "seller_subscriptions"  ("sellerId", "isActive") `);
        await queryRunner.query(`CREATE TYPE "public"."inventory_movements_type_enum" AS ENUM('in', 'sold', 'returned', 'expired', 'adjusted')`);
        await queryRunner.query(`CREATE TABLE "inventory_movements" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "productVariantId" uuid NOT NULL, "type" "public"."inventory_movements_type_enum" NOT NULL, "quantity" integer NOT NULL, "beforeStock" integer NOT NULL, "afterStock" integer NOT NULL, "reason" character varying(256), "orderId" uuid, "performedByUserId" uuid, "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_d7597827c1dcffae889db3ab873" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_3725f350c287cd1b92d6f14a44" ON "inventory_movements"  ("createdAt") `);
        await queryRunner.query(`CREATE INDEX "IDX_5c740da110af2e5dbf8b57c507" ON "inventory_movements"  ("productVariantId") `);
        await queryRunner.query(`CREATE TABLE "stock_batches" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "productVariantId" uuid NOT NULL, "shopId" uuid NOT NULL, "costPrice" integer NOT NULL DEFAULT '0', "quantityReceived" integer NOT NULL, "quantityRemaining" integer NOT NULL, "expiryDate" date, "supplierName" character varying(256), "note" character varying(256), "isReturn" boolean NOT NULL DEFAULT false, "performedByUserId" uuid, "receivedAt" TIMESTAMP WITH TIME ZONE NOT NULL, "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_85b4f081f5a5c69009675db8b1f" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_facc7168e603c07f112ff6a586" ON "stock_batches"  ("expiryDate") `);
        await queryRunner.query(`CREATE INDEX "IDX_1d1756f2d184538ea66778fe2d" ON "stock_batches"  ("receivedAt") `);
        await queryRunner.query(`CREATE INDEX "IDX_f7945761012cd6d49e7f0f27d6" ON "stock_batches"  ("productVariantId", "quantityRemaining") `);
        await queryRunner.query(`CREATE INDEX "IDX_46c3da93c82f452f3aed696462" ON "stock_batches"  ("shopId") `);
        await queryRunner.query(`CREATE INDEX "IDX_a3a96de39dccdf4ca904c6fdb0" ON "stock_batches"  ("productVariantId") `);
        await queryRunner.query(`CREATE TABLE "promotions" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "shopId" uuid NOT NULL, "name" character varying(128) NOT NULL, "type" character varying(32) NOT NULL, "discountType" character varying(16), "discountValue" integer, "targetProductId" uuid, "targetCategoryId" uuid, "freeDeliveryMinAmount" integer, "startAt" TIMESTAMP WITH TIME ZONE NOT NULL, "endAt" TIMESTAMP WITH TIME ZONE, "isActive" boolean NOT NULL DEFAULT true, "createdByUserId" uuid NOT NULL, "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_380cecbbe3ac11f0e5a7c452c34" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_ccad84d1ee5deea3be51b3aa92" ON "promotions"  ("shopId", "isActive") `);
        await queryRunner.query(`CREATE INDEX "IDX_00441b80473cfc564fd0726839" ON "promotions"  ("shopId") `);
        await queryRunner.query(`CREATE TABLE "device_tokens" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "userId" uuid, "token" character varying(256) NOT NULL, "platform" character varying(16) NOT NULL DEFAULT 'android', "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_84700be257607cfb1f9dc2e52c3" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_977e24c520c49436d08e5eeea8" ON "device_tokens"  ("token") `);
        await queryRunner.query(`CREATE INDEX "IDX_511957e3e8443429dc3fb00120" ON "device_tokens"  ("userId") `);
        await queryRunner.query(`CREATE TYPE "public"."seller_applications_status_enum" AS ENUM('pending', 'approved', 'rejected')`);
        await queryRunner.query(`CREATE TABLE "seller_applications" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "userId" uuid NOT NULL, "firstName" character varying(64) NOT NULL, "lastName" character varying(64) NOT NULL, "contactPhone" character varying(32), "note" text, "status" "public"."seller_applications_status_enum" NOT NULL DEFAULT 'pending', "rejectionReason" text, "reviewedByUserId" uuid, "reviewedAt" TIMESTAMP WITH TIME ZONE, "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_203be9b9b1f8ff560e8af1f90a5" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_2c6b7afed8e0d1698bfdd8e6bb" ON "seller_applications"  ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_bc16b54496faa4ffae868a999c" ON "seller_applications"  ("userId") `);
        await queryRunner.query(`CREATE TABLE "seller_profiles" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "userId" uuid NOT NULL, "fullName" character varying(128), "passportOrPinfl" character varying(64), "stir" character varying(16), "bankCardNumber" character varying(32), "bankCardHolderName" character varying(128), "entityType" character varying(64), "contractNumber" character varying(64), "contractDate" date, "verifiedAt" TIMESTAMP WITH TIME ZONE, "verifiedByAdminId" uuid, "adminNotes" text, "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "UQ_49de7dde25d76b120677be9aedd" UNIQUE ("userId"), CONSTRAINT "PK_13845670b88adfde01026410969" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_49de7dde25d76b120677be9aed" ON "seller_profiles"  ("userId") `);
        await queryRunner.query(`CREATE TABLE "global_settings" ("key" character varying(64) NOT NULL, "value" character varying(256) NOT NULL, "description" text, "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_53409270b1d43100e07099f1cca" PRIMARY KEY ("key"))`);
        await queryRunner.query(`CREATE TABLE "shop_staff" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "shopId" uuid NOT NULL, "userId" uuid NOT NULL, "customRoleName" character varying(64) NOT NULL, "preset" character varying(32) NOT NULL DEFAULT 'custom', "permissions" jsonb NOT NULL DEFAULT '[]'::jsonb, "isActive" boolean NOT NULL DEFAULT true, "removedAt" TIMESTAMP WITH TIME ZONE, "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "UQ_b4988ef771e5c5d5014c6e08168" UNIQUE ("shopId", "userId"), CONSTRAINT "PK_9bba17a9850aa21b019db9bc2ab" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_20badedcd625540c75a8b14b8f" ON "shop_staff"  ("userId") `);
        await queryRunner.query(`CREATE INDEX "IDX_4c4cbd01cd001a5f44404ab4b2" ON "shop_staff"  ("shopId") `);
        await queryRunner.query(`CREATE TYPE "public"."staff_invitations_status_enum" AS ENUM('pending', 'accepted', 'rejected', 'expired')`);
        await queryRunner.query(`CREATE TABLE "staff_invitations" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "shopId" uuid NOT NULL, "invitedByUserId" uuid NOT NULL, "customRoleName" character varying(64) NOT NULL, "preset" character varying(32) NOT NULL, "permissions" jsonb NOT NULL DEFAULT '[]'::jsonb, "qrToken" character varying(64) NOT NULL, "status" "public"."staff_invitations_status_enum" NOT NULL DEFAULT 'pending', "acceptedByUserId" uuid, "acceptedAt" TIMESTAMP WITH TIME ZONE, "expiresAt" TIMESTAMP WITH TIME ZONE NOT NULL, "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_842e5346c92d8003bdb2140b6c8" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_48a2a77d652ae2ba92084d6af3" ON "staff_invitations"  ("qrToken") `);
        await queryRunner.query(`CREATE INDEX "IDX_81becb57dfcf2d5ba43895fb22" ON "staff_invitations"  ("shopId") `);
        await queryRunner.query(`ALTER TABLE "categories" ADD CONSTRAINT "FK_9a6f051e66982b5f0318981bcaa" FOREIGN KEY ("parentId") REFERENCES "categories"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "notifications" ADD CONSTRAINT "FK_692a909ee0fa9383e7859f9b406" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "shops" ADD CONSTRAINT "FK_9f222a91f08322c9d08a1b443b8" FOREIGN KEY ("ownerId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_addresses" ADD CONSTRAINT "FK_781afdedafe920f331f6229cb62" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "global_products" ADD CONSTRAINT "FK_49e95d62d694529791c91ec26d3" FOREIGN KEY ("categoryId") REFERENCES "categories"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "global_products" ADD CONSTRAINT "FK_4bf7609c1c77d52950be6acc5a8" FOREIGN KEY ("parentGlobalProductId") REFERENCES "global_products"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "product_variants" ADD CONSTRAINT "FK_f0fc8814e8aded9e9ee5793199e" FOREIGN KEY ("shopId") REFERENCES "shops"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "product_variants" ADD CONSTRAINT "FK_e1f34b679c60762b30a747310e7" FOREIGN KEY ("globalProductId") REFERENCES "global_products"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "order_items" ADD CONSTRAINT "FK_f1d359a55923bb45b057fbdab0d" FOREIGN KEY ("orderId") REFERENCES "orders"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "order_items" ADD CONSTRAINT "FK_9cf6578d9f8c7f43cc96c7af6d8" FOREIGN KEY ("productVariantId") REFERENCES "product_variants"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "orders" ADD CONSTRAINT "FK_151b79a83ba240b0cb31b2302d1" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "orders" ADD CONSTRAINT "FK_7fc658e494680d44c3cc59b31b4" FOREIGN KEY ("shopId") REFERENCES "shops"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "orders" ADD CONSTRAINT "FK_749e5d7152b6cde429099a99530" FOREIGN KEY ("deliveryAddressId") REFERENCES "user_addresses"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "chat_messages" ADD CONSTRAINT "FK_b6c8d489c57f92b5e8dc818cf58" FOREIGN KEY ("orderId") REFERENCES "orders"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "chat_messages" ADD CONSTRAINT "FK_279b22f49e10e3fae432d3ce8be" FOREIGN KEY ("senderUserId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "reviews" ADD CONSTRAINT "FK_7ed5659e7139fc8bc039198cc1f" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "reviews" ADD CONSTRAINT "FK_2fd6e4869fe14144d8176e4360b" FOREIGN KEY ("productVariantId") REFERENCES "product_variants"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "reviews" ADD CONSTRAINT "FK_53a68dc905777554b7f702791fa" FOREIGN KEY ("orderId") REFERENCES "orders"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "seller_subscriptions" ADD CONSTRAINT "FK_f6cfcb4e39a9d0df814667bbf9d" FOREIGN KEY ("planId") REFERENCES "prime_plans"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "inventory_movements" ADD CONSTRAINT "FK_5c740da110af2e5dbf8b57c507d" FOREIGN KEY ("productVariantId") REFERENCES "product_variants"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "stock_batches" ADD CONSTRAINT "FK_a3a96de39dccdf4ca904c6fdb0f" FOREIGN KEY ("productVariantId") REFERENCES "product_variants"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "promotions" ADD CONSTRAINT "FK_8c41f03ea260440b291b9c1e5b5" FOREIGN KEY ("targetProductId") REFERENCES "product_variants"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "promotions" ADD CONSTRAINT "FK_ad806a3c521915753d93fb1d846" FOREIGN KEY ("targetCategoryId") REFERENCES "categories"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "device_tokens" ADD CONSTRAINT "FK_511957e3e8443429dc3fb00120c" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "seller_applications" ADD CONSTRAINT "FK_bc16b54496faa4ffae868a999ce" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "seller_profiles" ADD CONSTRAINT "FK_49de7dde25d76b120677be9aedd" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "shop_staff" ADD CONSTRAINT "FK_4c4cbd01cd001a5f44404ab4b2c" FOREIGN KEY ("shopId") REFERENCES "shops"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "shop_staff" ADD CONSTRAINT "FK_20badedcd625540c75a8b14b8ff" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "staff_invitations" ADD CONSTRAINT "FK_81becb57dfcf2d5ba43895fb22a" FOREIGN KEY ("shopId") REFERENCES "shops"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "staff_invitations" DROP CONSTRAINT "FK_81becb57dfcf2d5ba43895fb22a"`);
        await queryRunner.query(`ALTER TABLE "shop_staff" DROP CONSTRAINT "FK_20badedcd625540c75a8b14b8ff"`);
        await queryRunner.query(`ALTER TABLE "shop_staff" DROP CONSTRAINT "FK_4c4cbd01cd001a5f44404ab4b2c"`);
        await queryRunner.query(`ALTER TABLE "seller_profiles" DROP CONSTRAINT "FK_49de7dde25d76b120677be9aedd"`);
        await queryRunner.query(`ALTER TABLE "seller_applications" DROP CONSTRAINT "FK_bc16b54496faa4ffae868a999ce"`);
        await queryRunner.query(`ALTER TABLE "device_tokens" DROP CONSTRAINT "FK_511957e3e8443429dc3fb00120c"`);
        await queryRunner.query(`ALTER TABLE "promotions" DROP CONSTRAINT "FK_ad806a3c521915753d93fb1d846"`);
        await queryRunner.query(`ALTER TABLE "promotions" DROP CONSTRAINT "FK_8c41f03ea260440b291b9c1e5b5"`);
        await queryRunner.query(`ALTER TABLE "stock_batches" DROP CONSTRAINT "FK_a3a96de39dccdf4ca904c6fdb0f"`);
        await queryRunner.query(`ALTER TABLE "inventory_movements" DROP CONSTRAINT "FK_5c740da110af2e5dbf8b57c507d"`);
        await queryRunner.query(`ALTER TABLE "seller_subscriptions" DROP CONSTRAINT "FK_f6cfcb4e39a9d0df814667bbf9d"`);
        await queryRunner.query(`ALTER TABLE "reviews" DROP CONSTRAINT "FK_53a68dc905777554b7f702791fa"`);
        await queryRunner.query(`ALTER TABLE "reviews" DROP CONSTRAINT "FK_2fd6e4869fe14144d8176e4360b"`);
        await queryRunner.query(`ALTER TABLE "reviews" DROP CONSTRAINT "FK_7ed5659e7139fc8bc039198cc1f"`);
        await queryRunner.query(`ALTER TABLE "chat_messages" DROP CONSTRAINT "FK_279b22f49e10e3fae432d3ce8be"`);
        await queryRunner.query(`ALTER TABLE "chat_messages" DROP CONSTRAINT "FK_b6c8d489c57f92b5e8dc818cf58"`);
        await queryRunner.query(`ALTER TABLE "orders" DROP CONSTRAINT "FK_749e5d7152b6cde429099a99530"`);
        await queryRunner.query(`ALTER TABLE "orders" DROP CONSTRAINT "FK_7fc658e494680d44c3cc59b31b4"`);
        await queryRunner.query(`ALTER TABLE "orders" DROP CONSTRAINT "FK_151b79a83ba240b0cb31b2302d1"`);
        await queryRunner.query(`ALTER TABLE "order_items" DROP CONSTRAINT "FK_9cf6578d9f8c7f43cc96c7af6d8"`);
        await queryRunner.query(`ALTER TABLE "order_items" DROP CONSTRAINT "FK_f1d359a55923bb45b057fbdab0d"`);
        await queryRunner.query(`ALTER TABLE "product_variants" DROP CONSTRAINT "FK_e1f34b679c60762b30a747310e7"`);
        await queryRunner.query(`ALTER TABLE "product_variants" DROP CONSTRAINT "FK_f0fc8814e8aded9e9ee5793199e"`);
        await queryRunner.query(`ALTER TABLE "global_products" DROP CONSTRAINT "FK_4bf7609c1c77d52950be6acc5a8"`);
        await queryRunner.query(`ALTER TABLE "global_products" DROP CONSTRAINT "FK_49e95d62d694529791c91ec26d3"`);
        await queryRunner.query(`ALTER TABLE "user_addresses" DROP CONSTRAINT "FK_781afdedafe920f331f6229cb62"`);
        await queryRunner.query(`ALTER TABLE "shops" DROP CONSTRAINT "FK_9f222a91f08322c9d08a1b443b8"`);
        await queryRunner.query(`ALTER TABLE "notifications" DROP CONSTRAINT "FK_692a909ee0fa9383e7859f9b406"`);
        await queryRunner.query(`ALTER TABLE "categories" DROP CONSTRAINT "FK_9a6f051e66982b5f0318981bcaa"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_81becb57dfcf2d5ba43895fb22"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_48a2a77d652ae2ba92084d6af3"`);
        await queryRunner.query(`DROP TABLE "staff_invitations"`);
        await queryRunner.query(`DROP TYPE "public"."staff_invitations_status_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_4c4cbd01cd001a5f44404ab4b2"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_20badedcd625540c75a8b14b8f"`);
        await queryRunner.query(`DROP TABLE "shop_staff"`);
        await queryRunner.query(`DROP TABLE "global_settings"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_49de7dde25d76b120677be9aed"`);
        await queryRunner.query(`DROP TABLE "seller_profiles"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_bc16b54496faa4ffae868a999c"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_2c6b7afed8e0d1698bfdd8e6bb"`);
        await queryRunner.query(`DROP TABLE "seller_applications"`);
        await queryRunner.query(`DROP TYPE "public"."seller_applications_status_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_511957e3e8443429dc3fb00120"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_977e24c520c49436d08e5eeea8"`);
        await queryRunner.query(`DROP TABLE "device_tokens"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_00441b80473cfc564fd0726839"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ccad84d1ee5deea3be51b3aa92"`);
        await queryRunner.query(`DROP TABLE "promotions"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_a3a96de39dccdf4ca904c6fdb0"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_46c3da93c82f452f3aed696462"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f7945761012cd6d49e7f0f27d6"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_1d1756f2d184538ea66778fe2d"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_facc7168e603c07f112ff6a586"`);
        await queryRunner.query(`DROP TABLE "stock_batches"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_5c740da110af2e5dbf8b57c507"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_3725f350c287cd1b92d6f14a44"`);
        await queryRunner.query(`DROP TABLE "inventory_movements"`);
        await queryRunner.query(`DROP TYPE "public"."inventory_movements_type_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ab10ec10133b7e1926a824880b"`);
        await queryRunner.query(`DROP TABLE "seller_subscriptions"`);
        await queryRunner.query(`DROP TABLE "prime_plans"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_960e0ec5dbbb52352401b84b6b"`);
        await queryRunner.query(`DROP TABLE "withdrawal_requests"`);
        await queryRunner.query(`DROP TYPE "public"."withdrawal_requests_status_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b9b774cc499fe064311e69b788"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_398f34204057deff8f37060f4a"`);
        await queryRunner.query(`DROP TABLE "seller_transactions"`);
        await queryRunner.query(`DROP TYPE "public"."seller_transactions_type_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f8e76a6290799a7971133b2fa2"`);
        await queryRunner.query(`DROP TABLE "seller_balances"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_2fd6e4869fe14144d8176e4360"`);
        await queryRunner.query(`DROP TABLE "reviews"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c13440c7163e7d349fee5ff8a5"`);
        await queryRunner.query(`DROP TABLE "chat_messages"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_151b79a83ba240b0cb31b2302d"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_7fc658e494680d44c3cc59b31b"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_775c9f06fc27ae3ff8fb26f2c4"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_1f4b9818a08b822a31493fdee9"`);
        await queryRunner.query(`DROP TABLE "orders"`);
        await queryRunner.query(`DROP TYPE "public"."orders_paymentstatus_enum"`);
        await queryRunner.query(`DROP TYPE "public"."orders_paymentmethod_enum"`);
        await queryRunner.query(`DROP TYPE "public"."orders_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."orders_channel_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f1d359a55923bb45b057fbdab0"`);
        await queryRunner.query(`DROP TABLE "order_items"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f0fc8814e8aded9e9ee5793199"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_94d7217a650df509004c9ef458"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e1f34b679c60762b30a747310e"`);
        await queryRunner.query(`DROP TABLE "product_variants"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_03af0d5bb5d7cfb8814b9c36ab"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f9d3e6d9c5bf426e72e8b18d48"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_4bf7609c1c77d52950be6acc5a"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_093da3874aeff5ab90cb7cb8ca"`);
        await queryRunner.query(`DROP TABLE "global_products"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_781afdedafe920f331f6229cb6"`);
        await queryRunner.query(`DROP TABLE "user_addresses"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_9f222a91f08322c9d08a1b443b"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_d38394b318a963074a1db6d5ff"`);
        await queryRunner.query(`DROP TABLE "shops"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_21e65af2f4f242d4c85a92aff4"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_5340fc241f57310d243e5ab20b"`);
        await queryRunner.query(`DROP TABLE "notifications"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_a000cca60bcf04454e72769949"`);
        await queryRunner.query(`DROP TABLE "users"`);
        await queryRunner.query(`DROP TYPE "public"."users_status_enum"`);
        await queryRunner.query(`DROP TABLE "notification_templates"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_18f03a4157df01362487561a89"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_861450059455369c652646c0cd"`);
        await queryRunner.query(`DROP TABLE "debts"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_8c90ebeaecf5a829dc3a9bf779"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_dd551fbae9b5c6d1a15a5c043e"`);
        await queryRunner.query(`DROP TABLE "debt_payments"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_189c4035e45c65e0585bf05ad5"`);
        await queryRunner.query(`DROP TABLE "contact_inquiries"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e973a07c51fc96d7e0ccb0faa1"`);
        await queryRunner.query(`DROP TABLE "chat_templates"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_420d9f679d41281f282f5bc7d0"`);
        await queryRunner.query(`DROP TABLE "categories"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_87c877cbe4318d54eda893b7af"`);
        await queryRunner.query(`DROP TABLE "app_releases"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_eed5678b20baa095e18ceb464a"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_2583a18597840d00d7f2f9604c"`);
        await queryRunner.query(`DROP TABLE "click_payment_transaction"`);
        await queryRunner.query(`DROP TYPE "public"."click_payment_transaction_status_enum"`);
    }

}
